User Model
fedesmpz/PF-E-Latam pull request #17
Opened 2023-06-12 20:10 UTC by CristianR1992

**Modelo Usuario**

2023-06-12 20:13 UTC, Victoria-Barrientos requested changes
Falta propiedad apellido (surname), carrito_ID vendria como Foreign key desde la tabla relacional. Tambien, no estoy de acuerdo con que se guarde password en el modelo. Pues no se guarda la password. Se verifica solamente

2023-06-12 20:15 UTC, fedesmpz approved these changes

2023-06-12 20:31 UTC, CristianR1992 commented
Me guie por la tabla, y no habiamos puesto surname.. ahi lo agrego... el tema de que si solo lo validamos donde la guardamos? en la base de dato llegaria y se guardaria encriptada.

Tenes razon lo del carrito_id , se crea dsp con la relacion

2023-06-12 20:59 UTC, fedesmpz approved these changes

2023-06-12 21:32 UTC, parzybaal commented
tendría que guardarte con el auth las credenciales del usuario

2023-06-12 21:40 UTC, parzybaal approved these changes
LGFM

2023-06-13 00:08 UTC, camilobit approved these changes

2023-06-13 11:43 UTC, Victoria-Barrientos approved these changes
Genial Cris! Si, ya se que no estaba surname.. yo que hice admin model tambien me toco agregarlo. Nos olvidamos de ponerlo

2023-06-13 11:43 UTC, merged